version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "softcomweb-api-sqs-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oaqw1liyr7g1"
s3_prefix = "softcomweb-api-sqs-lambda"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ServiceName=\"ApigwSqsLambda\" Environment=\"Staging\""
